/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package kasir;

import admin.*;
import java.awt.BorderLayout;
import config.UserSession;
import login.halaman_login;
import javax.swing.JOptionPane;
import javax.swing.AbstractAction;
import javax.swing.ActionMap;
import javax.swing.InputMap;
import javax.swing.JComponent;
import javax.swing.KeyStroke;
import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;

/**
 *
 * @author user
 */
public class dashboard_kasir extends javax.swing.JFrame {

    /**
     * Creates new form admin
     */
    public dashboard_kasir() {
        initComponents();
        setupDashboardKeyBindings();

        A_txt_2.setText(UserSession.getUsername().toUpperCase());

        // Otomatis menampilkan beranda kasir saat dashboard terbuka
        beranda_kasir beranda = new beranda_kasir();
        showPanel(beranda);
        
    }

    private void showPanel(javax.swing.JPanel panel) {
        K_panel_utama.removeAll();
        K_panel_utama.setLayout(new java.awt.BorderLayout());
        K_panel_utama.add(panel, java.awt.BorderLayout.CENTER);
        K_panel_utama.revalidate();
        K_panel_utama.repaint();
    }
    
    private void setupDashboardKeyBindings() {
    // Dapatkan InputMap dan ActionMap dari root pane JFrame
    InputMap inputMap = this.getRootPane().getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW);
    ActionMap actionMap = this.getRootPane().getActionMap();

    // -- Shortcut ALT + 1 untuk Beranda --
    KeyStroke alt1KeyStroke = KeyStroke.getKeyStroke(KeyEvent.VK_1, KeyEvent.ALT_DOWN_MASK);
    inputMap.put(alt1KeyStroke, "berandaAction");
    actionMap.put("berandaAction", new AbstractAction() {
        @Override
        public void actionPerformed(ActionEvent e) {
            K_btn_beranda.doClick(); // Simulasikan klik tombol Beranda
        }
    });

    // -- Shortcut ALT + 2 untuk Kasir --
    KeyStroke alt2KeyStroke = KeyStroke.getKeyStroke(KeyEvent.VK_2, KeyEvent.ALT_DOWN_MASK);
    inputMap.put(alt2KeyStroke, "kasirAction");
    actionMap.put("kasirAction", new AbstractAction() {
        @Override
        public void actionPerformed(ActionEvent e) {
            K_btn_kasir.doClick(); // Simulasikan klik tombol Kasir
        }
    });

    // -- Shortcut ALT + 3 untuk Daftar Barang --
    KeyStroke alt3KeyStroke = KeyStroke.getKeyStroke(KeyEvent.VK_3, KeyEvent.ALT_DOWN_MASK);
    inputMap.put(alt3KeyStroke, "daftarBarangAction");
    actionMap.put("daftarBarangAction", new AbstractAction() {
        @Override
        public void actionPerformed(ActionEvent e) {
            K_btn_daftar_barang.doClick(); // Simulasikan klik tombol Daftar Barang
        }
    });

    // -- Shortcut ALT + SHIFT + ENTER untuk Logout --
    KeyStroke altShiftEnterKeyStroke = KeyStroke.getKeyStroke(KeyEvent.VK_ENTER, KeyEvent.ALT_DOWN_MASK | KeyEvent.SHIFT_DOWN_MASK);
    inputMap.put(altShiftEnterKeyStroke, "logoutAction");
    actionMap.put("logoutAction", new AbstractAction() {
        @Override
        public void actionPerformed(ActionEvent e) {
            K_btn_logout.doClick(); // Simulasikan klik tombol Logout
        }
    });
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        A_txt_1 = new javax.swing.JLabel();
        K_btn_logout = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        A_txt_2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        K_btn_beranda = new javax.swing.JButton();
        K_btn_daftar_barang = new javax.swing.JButton();
        K_btn_kasir = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        K_panel_utama = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(1920, 1080));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 102));
        jPanel1.setMinimumSize(new java.awt.Dimension(1870, 100));
        jPanel1.setPreferredSize(new java.awt.Dimension(1920, 100));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        A_txt_1.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        A_txt_1.setForeground(new java.awt.Color(255, 255, 255));
        A_txt_1.setText("KASIR SAKPORE");
        jPanel1.add(A_txt_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, 720, 100));

        K_btn_logout.setBackground(new java.awt.Color(0, 51, 51));
        K_btn_logout.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        K_btn_logout.setForeground(new java.awt.Color(255, 255, 255));
        K_btn_logout.setText("LOGOUT");
        K_btn_logout.setMaximumSize(new java.awt.Dimension(70, 70));
        K_btn_logout.setMinimumSize(new java.awt.Dimension(70, 70));
        K_btn_logout.setPreferredSize(new java.awt.Dimension(70, 70));
        K_btn_logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                K_btn_logoutActionPerformed(evt);
            }
        });
        jPanel1.add(K_btn_logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(1750, 40, 130, 40));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Posisi : KASIR");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1530, 60, 220, 30));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 100)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("=");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 80, 80));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 100)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("=");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 80, 80));

        A_txt_2.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        A_txt_2.setForeground(new java.awt.Color(255, 255, 255));
        A_txt_2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        A_txt_2.setText("ALMADANI");
        jPanel1.add(A_txt_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1530, 30, 220, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1920, 120));

        jPanel2.setBackground(java.awt.Color.gray);
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        K_btn_beranda.setBackground(java.awt.Color.darkGray);
        K_btn_beranda.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        K_btn_beranda.setForeground(new java.awt.Color(255, 255, 255));
        K_btn_beranda.setText("BERANDA");
        K_btn_beranda.setOpaque(true);
        K_btn_beranda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                K_btn_berandaActionPerformed(evt);
            }
        });
        jPanel2.add(K_btn_beranda, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 200, 60));

        K_btn_daftar_barang.setBackground(java.awt.Color.darkGray);
        K_btn_daftar_barang.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        K_btn_daftar_barang.setForeground(new java.awt.Color(255, 255, 255));
        K_btn_daftar_barang.setText("DAFTAR BARANG");
        K_btn_daftar_barang.setOpaque(true);
        K_btn_daftar_barang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                K_btn_daftar_barangActionPerformed(evt);
            }
        });
        jPanel2.add(K_btn_daftar_barang, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 200, 60));

        K_btn_kasir.setBackground(java.awt.Color.darkGray);
        K_btn_kasir.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        K_btn_kasir.setForeground(new java.awt.Color(255, 255, 255));
        K_btn_kasir.setText("KASIR");
        K_btn_kasir.setOpaque(true);
        K_btn_kasir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                K_btn_kasirActionPerformed(evt);
            }
        });
        jPanel2.add(K_btn_kasir, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 200, 60));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("PINDAH TAP HALAMAN");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 200, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("[ ALT + 1,2,3.... }");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 200, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 220, 960));

        K_panel_utama.setBackground(new java.awt.Color(255, 255, 255));
        K_panel_utama.setMinimumSize(new java.awt.Dimension(1650, 940));

        javax.swing.GroupLayout K_panel_utamaLayout = new javax.swing.GroupLayout(K_panel_utama);
        K_panel_utama.setLayout(K_panel_utamaLayout);
        K_panel_utamaLayout.setHorizontalGroup(
            K_panel_utamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1680, Short.MAX_VALUE)
        );
        K_panel_utamaLayout.setVerticalGroup(
            K_panel_utamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 940, Short.MAX_VALUE)
        );

        getContentPane().add(K_panel_utama, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 130, 1680, 940));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void K_btn_berandaActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_K_btn_berandaActionPerformed
        // TODO add your handling code here:
        beranda_kasir panel = new beranda_kasir();
        showPanel(panel);
    }// GEN-LAST:event_K_btn_berandaActionPerformed

    private void K_btn_daftar_barangActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_K_btn_daftar_barangActionPerformed
        // TODO add your handling code here:
        admin.daftar_barang panel = new admin.daftar_barang("Kasir");
        showPanel(panel);
    }// GEN-LAST:event_K_btn_daftar_barangActionPerformed

    private void K_btn_kasirActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_K_btn_kasirActionPerformed
        // TODO add your handling code here:
        kasir panel = new kasir();
        showPanel(panel);
        showKasirPanel();
    }// GEN-LAST:event_K_btn_kasirActionPerformed

    private void K_btn_logoutActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_K_btn_logoutActionPerformed
        // TODO add your handling code here:
        int confirm = JOptionPane.showConfirmDialog(this,
                "Apakah Anda yakin ingin logout?",
                "Konfirmasi Logout",
                JOptionPane.YES_NO_OPTION);

        if (confirm == JOptionPane.YES_OPTION) {
            UserSession.clearSession(); // Hapus sesi
            this.dispose(); // Tutup dashboard
            new halaman_login().setVisible(true); // Buka halaman login
        }
    }// GEN-LAST:event_K_btn_logoutActionPerformed

    public void showKasirPanel() {
        kasir panel = new kasir();
        showPanel(panel);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(dashboard_kasir.class.getName()).log(java.util.logging.Level.SEVERE,
                    null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(dashboard_kasir.class.getName()).log(java.util.logging.Level.SEVERE,
                    null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(dashboard_kasir.class.getName()).log(java.util.logging.Level.SEVERE,
                    null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(dashboard_kasir.class.getName()).log(java.util.logging.Level.SEVERE,
                    null, ex);
        }
        // </editor-fold>
        // </editor-fold>
        // </editor-fold>
        // </editor-fold>
        // </editor-fold>
        // </editor-fold>
        // </editor-fold>
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new dashboard_kasir().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel A_txt_1;
    private javax.swing.JLabel A_txt_2;
    private javax.swing.JButton K_btn_beranda;
    private javax.swing.JButton K_btn_daftar_barang;
    private javax.swing.JButton K_btn_kasir;
    private javax.swing.JButton K_btn_logout;
    private javax.swing.JPanel K_panel_utama;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
